const char *frg_shdr_src =
"// gears.fs\n"
"//\n"
"// Emulates a fixed function pipeline with:\n"
"//  GL_ALPHA_TEST is disabled by default\n"
"//  GL_BLEND is disabled by default\n"
"//  GL_FOG disabled\n"
"//  GL_TEXTURE_xx disabled\n"
"//\n"
"//  Since alpha test and blend are both disabled, there is no need to keep track\n"
"//  of the alpha component in the fragment shader.\n"
"\n"
"// global foreground alpha\n"
"uniform lowp float fgAlpha;\n"
"\n"
"// interpolated per-vertex lighting\n"
"varying lowp vec3 Color;\n"
"\n"
"void main(void)\n"
"{\n"
"  // this is the second-simplest fragment shader\n"
"  gl_FragColor = vec4(Color, fgAlpha);\n"
"}\n";
